### PR TITLE
Push excel improvements

### PR DESCRIPTION
**Pull request by anuveyatsu**
This PR fixes following issues:

- https://github.com/datahq/data-cli/issues/258
- https://github.com/datahq/data-cli/issues/260

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@zelima this would be another feature, initially, we didn't plan this. I think it's sufficient to only allow select sheet by index and we can consider "selecting by name" feature if there is a request from a user.

**Comment by zelima** [comment]
@anuveyatsu agree. 

@AcckiyGerman could you please open issue about pushing excel files by sheet names and place it inside this Epic https://github.com/datahq/datahub-qa/issues/78

**Comment by AcckiyGerman** [comment]
**Pushing excel data by the sheet name** - https://github.com/datahq/datahub-qa/issues/88

**Comment by AcckiyGerman** [comment]
FIXED.
If an empty sheet is pointed by user, the program will reply with `> Error! You cannot push an empty sheet. Please, add some data and try again.`

**Pull request merged**
